# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/proj/XADC_Demo.cache/wt [current_project]
set_property parent.project_path /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/proj/XADC_Demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/repo [current_project]
add_files -quiet /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/ip/xadc_wiz_0/xadc_wiz_0.dcp
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/ip/xadc_wiz_0/xadc_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/hdl/sevensegdecoder.v
  /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/hdl/segClkDevider.v
  /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/hdl/mux4_4bus.v
  /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/hdl/decoder3_8.v
  /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/hdl/counter3bit.v
  /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/proj/XADC_Demo.srcs/sources_1/new/ADCController.v
  /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/hdl/DigitToSeg.v
  /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/hdl/XADCdemo.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/constraints/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/d/d/ddr/6.111/project_xadc/src/constraints/Nexys4DDR_Master.xdc]


synth_design -top XADCdemo -part xc7a100tcsg324-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef XADCdemo.dcp

catch { report_utilization -file XADCdemo_utilization_synth.rpt -pb XADCdemo_utilization_synth.pb }
