# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/athena.mit.edu/user/d/d/ddr/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.srcs/sources_1/ip/shift_ram_4cycledelay/shift_ram_4cycledelay.xci
# IP: The module: 'shift_ram_4cycledelay' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/d/d/ddr/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.srcs/sources_1/ip/shift_ram_4cycledelay/shift_ram_4cycledelay_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_ram_4cycledelay'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /afs/athena.mit.edu/user/d/d/ddr/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.srcs/sources_1/ip/shift_ram_4cycledelay/shift_ram_4cycledelay.xci
# IP: The module: 'shift_ram_4cycledelay' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/d/d/ddr/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.srcs/sources_1/ip/shift_ram_4cycledelay/shift_ram_4cycledelay_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_ram_4cycledelay'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
