set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.runs/synth_1/.Xil/Vivado-6135-eecs-digital-02/dcp/blk_mem_gen_0_in_context.xdc rfile:../dcp/blk_mem_gen_0_in_context.xdc id:1 order:EARLY scoped_inst:BufferChannel1/bram0} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.runs/synth_1/.Xil/Vivado-6135-eecs-digital-02/dcp/blk_mem_gen_0_in_context.xdc rfile:../dcp/blk_mem_gen_0_in_context.xdc id:2 order:EARLY scoped_inst:BufferChannel1/bram1} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.runs/synth_1/.Xil/Vivado-6135-eecs-digital-02/dcp/blk_mem_gen_0_in_context.xdc rfile:../dcp/blk_mem_gen_0_in_context.xdc id:3 order:EARLY scoped_inst:Buffer2Channel1/bram0} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.runs/synth_1/.Xil/Vivado-6135-eecs-digital-02/dcp/blk_mem_gen_0_in_context.xdc rfile:../dcp/blk_mem_gen_0_in_context.xdc id:4 order:EARLY scoped_inst:Buffer2Channel1/bram1} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.runs/synth_1/.Xil/Vivado-6135-eecs-digital-02/dcp/blk_mem_gen_0_in_context.xdc rfile:../dcp/blk_mem_gen_0_in_context.xdc id:5 order:EARLY scoped_inst:BufferChannel2/bram0} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.runs/synth_1/.Xil/Vivado-6135-eecs-digital-02/dcp/blk_mem_gen_0_in_context.xdc rfile:../dcp/blk_mem_gen_0_in_context.xdc id:6 order:EARLY scoped_inst:BufferChannel2/bram1} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.runs/synth_1/.Xil/Vivado-6135-eecs-digital-02/dcp/blk_mem_gen_0_in_context.xdc rfile:../dcp/blk_mem_gen_0_in_context.xdc id:7 order:EARLY scoped_inst:Buffer2Channel2/bram0} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.runs/synth_1/.Xil/Vivado-6135-eecs-digital-02/dcp/blk_mem_gen_0_in_context.xdc rfile:../dcp/blk_mem_gen_0_in_context.xdc id:8 order:EARLY scoped_inst:Buffer2Channel2/bram1} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.runs/synth_1/.Xil/Vivado-6135-eecs-digital-02/dcp_2/CharactersROM_in_context.xdc rfile:../dcp_2/CharactersROM_in_context.xdc id:9 order:EARLY scoped_inst:myText/characterBRAM} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.runs/synth_1/.Xil/Vivado-6135-eecs-digital-02/dcp_3/clk_wiz_0_in_context.xdc rfile:../dcp_3/clk_wiz_0_in_context.xdc id:10 order:EARLY scoped_inst:ClockDivider} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/j/a/jatron/Documents/6.111/6.111-Final-Project/Oscilloscope_v1/Oscilloscope_v1.srcs/constrs_1/imports/constraints/Nexys4DDR_Master.xdc rfile:../../../../../Oscilloscope_v1.srcs/constrs_1/imports/constraints/Nexys4DDR_Master.xdc id:11} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins BufferChannel1/bram0/clka]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins BufferChannel1/bram0/clkb]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells BufferChannel1/bram0]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins BufferChannel1/bram1/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins BufferChannel1/bram1/clkb]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells BufferChannel1/bram1]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins Buffer2Channel1/bram0/clka]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins Buffer2Channel1/bram0/clkb]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells Buffer2Channel1/bram0]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins Buffer2Channel1/bram1/clka]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins Buffer2Channel1/bram1/clkb]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells Buffer2Channel1/bram1]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins BufferChannel2/bram0/clka]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins BufferChannel2/bram0/clkb]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells BufferChannel2/bram0]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins BufferChannel2/bram1/clka]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins BufferChannel2/bram1/clkb]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells BufferChannel2/bram1]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins Buffer2Channel2/bram0/clka]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins Buffer2Channel2/bram0/clkb]
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells Buffer2Channel2/bram0]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins Buffer2Channel2/bram1/clka]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins Buffer2Channel2/bram1/clkb]
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells Buffer2Channel2/bram1]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins myText/characterBRAM/clka]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins myText/characterBRAM/clkb]
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells myText/characterBRAM]
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:10 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:10 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ClockDivider]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name CLK100MHZ [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports CLK100MHZ] -edges {1 2 3} -edge_shift {0.000 -0.370 -0.741} [get_pins ClockDivider/clk_out1]
set_property src_info {type:XDC file:11 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK100MHZ]
